#include "currencyiso.h"

namespace dex {

CurrencyIso::CurrencyIso()
{
    initListIso();
}

bool CurrencyIso::isValid(const std::string &iso)
{
    if (setIso.count(iso) > 0) {
        return true;
    }

    return false;
}

void CurrencyIso::initListIso()
{
    setIso.clear();
    setIso.insert("AED");
    setIso.insert("AFN");
    setIso.insert("ALL");
    setIso.insert("AMD");
    setIso.insert("ANG");
    setIso.insert("AOA");
    setIso.insert("ARS");
    setIso.insert("AUD");
    setIso.insert("AWG");
    setIso.insert("AZN");
    setIso.insert("BAM");
    setIso.insert("BBD");
    setIso.insert("BDT");
    setIso.insert("BGN");
    setIso.insert("BHD");
    setIso.insert("BIF");
    setIso.insert("BMD");
    setIso.insert("BND");
    setIso.insert("BOB");
    setIso.insert("BOV");
    setIso.insert("BRL");
    setIso.insert("BSD");
    setIso.insert("BTN");
    setIso.insert("BWP");
    setIso.insert("BYR");
    setIso.insert("BZD");
    setIso.insert("CAD");
    setIso.insert("CDF");
    setIso.insert("CHE");
    setIso.insert("CHF");
    setIso.insert("CHW");
    setIso.insert("CLF");
    setIso.insert("CLP");
    setIso.insert("CNY");
    setIso.insert("COP");
    setIso.insert("COU");
    setIso.insert("CRC");
    setIso.insert("CUP");
    setIso.insert("CVE");
    setIso.insert("CYP");
    setIso.insert("CZK");
    setIso.insert("DJF");
    setIso.insert("DKK");
    setIso.insert("DOP");
    setIso.insert("DZD");
    setIso.insert("EEK");
    setIso.insert("EGP");
    setIso.insert("ERN");
    setIso.insert("ETB");
    setIso.insert("EUR");
    setIso.insert("FJD");
    setIso.insert("FKP");
    setIso.insert("GBP");
    setIso.insert("GEL");
    setIso.insert("GHS");
    setIso.insert("GIP");
    setIso.insert("GMD");
    setIso.insert("GNF");
    setIso.insert("GTQ");
    setIso.insert("GYD");
    setIso.insert("HKD");
    setIso.insert("HNL");
    setIso.insert("HRK");
    setIso.insert("HTG");
    setIso.insert("HUF");
    setIso.insert("IDR");
    setIso.insert("ILS");
    setIso.insert("INR");
    setIso.insert("IQD");
    setIso.insert("IRR");
    setIso.insert("ISK");
    setIso.insert("JMD");
    setIso.insert("JOD");
    setIso.insert("JPY");
    setIso.insert("KES");
    setIso.insert("KGS");
    setIso.insert("KHR");
    setIso.insert("KMF");
    setIso.insert("KPW");
    setIso.insert("KRW");
    setIso.insert("KWD");
    setIso.insert("KYD");
    setIso.insert("KZT");
    setIso.insert("LAK");
    setIso.insert("LBP");
    setIso.insert("LKR");
    setIso.insert("LRD");
    setIso.insert("LSL");
    setIso.insert("LTL");
    setIso.insert("LVL");
    setIso.insert("LYD");
    setIso.insert("MAD");
    setIso.insert("MDL");
    setIso.insert("MGA");
    setIso.insert("MKD");
    setIso.insert("MMK");
    setIso.insert("MNT");
    setIso.insert("MOP");
    setIso.insert("MRO");
    setIso.insert("MTL");
    setIso.insert("MUR");
    setIso.insert("MVR");
    setIso.insert("MWK");
    setIso.insert("MXN");
    setIso.insert("MXV");
    setIso.insert("MYR");
    setIso.insert("MZN");
    setIso.insert("NAD");
    setIso.insert("NGN");
    setIso.insert("NIO");
    setIso.insert("NOK");
    setIso.insert("NPR");
    setIso.insert("NZD");
    setIso.insert("OMR");
    setIso.insert("PAB");
    setIso.insert("PEN");
    setIso.insert("PGK");
    setIso.insert("PHP");
    setIso.insert("PKR");
    setIso.insert("PLN");
    setIso.insert("PYG");
    setIso.insert("QAR");
    setIso.insert("RON");
    setIso.insert("RSD");
    setIso.insert("RUB");
    setIso.insert("RWF");
    setIso.insert("SAR");
    setIso.insert("SBD");
    setIso.insert("SCR");
    setIso.insert("SDG");
    setIso.insert("SEK");
    setIso.insert("SGD");
    setIso.insert("SHP");
    setIso.insert("SKK");
    setIso.insert("SLL");
    setIso.insert("SOS");
    setIso.insert("SRD");
    setIso.insert("SSP");
    setIso.insert("STD");
    setIso.insert("SYP");
    setIso.insert("SZL");
    setIso.insert("THB");
    setIso.insert("TJS");
    setIso.insert("TMM");
    setIso.insert("TND");
    setIso.insert("TOP");
    setIso.insert("TRY");
    setIso.insert("TTD");
    setIso.insert("TWD");
    setIso.insert("TZS");
    setIso.insert("UAH");
    setIso.insert("UGX");
    setIso.insert("USD");
    setIso.insert("USN");
    setIso.insert("USS");
    setIso.insert("UYU");
    setIso.insert("UZS");
    setIso.insert("VEB");
    setIso.insert("VEF");
    setIso.insert("VND");
    setIso.insert("VUV");
    setIso.insert("WST");
    setIso.insert("XAF");
    setIso.insert("XAG");
    setIso.insert("XAU");
    setIso.insert("XBA");
    setIso.insert("XBB");
    setIso.insert("XBC");
    setIso.insert("XBD");
    setIso.insert("XCD");
    setIso.insert("XDR");
    setIso.insert("XFO");
    setIso.insert("XFU");
    setIso.insert("XOF");
    setIso.insert("XPD");
    setIso.insert("XPF");
    setIso.insert("XPT");
    setIso.insert("XTS");
    setIso.insert("XXX");
    setIso.insert("YER");
    setIso.insert("ZAR");
    setIso.insert("ZMK");
    setIso.insert("ZWD");
}

}
